### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by wiio12** [albertqjiang/Portal-to-ISAbelle#18]
Hey there, I found some of the links in the readme have been broken, can you kindly fix them?

The examples:
> See [this](https://terminalizer.com/view/cb6ea5dd5395) for how to write proofs with a Python script with PISA.

Got access denied downloading the heap images.
> We built the heap images of Isabelle2021 with afp-2021-10-22 for linux machines (ubuntu). You can download it at: https://storage.googleapis.com/n2formal-public-data/isabelle_heaps.tar.gz and decompress it as ~/.isabelle.

Access denied downloading the extracted dataset.
>With a single process, the extraction takes ~5 days. This will extract files to the directory afp_extractions. We have also extracted this dataset, available for download at https://storage.googleapis.com/n2formal-public-data/afp_extractions.tar.gz.

**Comment by albertqjiang** [comment]
Hi thanks for pointing these out! Unfortunately I'm very occupied with other obligations at the moment and will come back to fixing these broken links as well as updating the repository in October.

**Comment by wiio12** [comment]
Thanks for your reply @albertqjiang! I'm looking forward to your updates :D.

**Comment by albertqjiang** [comment]
@wiio12 You can use 
https://archive.org/download/isabelle_heaps.tar/isabelle_heaps.tar.gz
and
https://archive.org/download/afp_extractions.tar/afp_extractions.tar.gz

for now. I will push to the main branch once the documentation is improved.

**Comment by wiio12** [comment]
Thanks a lot @albertqjiang!
